### ISSUE TITLE
module declares its path as: steampipe-plugin-mastodon  but was required as: github.com/turbot/steampipe-plugin-mastodon

### ISSUE THREAD

**Issue by judell** [turbot/steampipe-export#14]
make build plugin=mastodon
go run generate/generator.go templates . mastodon
4
filePath: /home/jon/steampipe-table-dump/templates
not a file, continuing...

filePath: /home/jon/steampipe-table-dump/templates/.goreleaser.yml.tmpl
filePath: /home/jon/steampipe-table-dump/templates/main.go.tmpl
filePath: /home/jon/steampipe-table-dump/templates/out
not a file, continuing...

filePath: /home/jon/steampipe-table-dump/templates/out/Makefile.tmpl
filePath: /home/jon/steampipe-table-dump/templates/out/README.md.tmpl
go mod tidy
go: finding module for package github.com/turbot/steampipe-plugin-mastodon/mastodon
go: downloading github.com/turbot/steampipe-plugin-mastodon v0.1.1
go: found github.com/turbot/steampipe-plugin-mastodon/mastodon in github.com/turbot/steampipe-plugin-mastodon v0.1.1
go: github.com/turbot/steampipe-table-dump imports
        github.com/turbot/steampipe-plugin-mastodon/mastodon: github.com/turbot/steampipe-plugin-mastodon@v0.1.1: parsing go.mod:
        module declares its path as: steampipe-plugin-mastodon
                but was required as: github.com/turbot/steampipe-plugin-mastodon
make: *** [Makefile:9: build] Error 1

**Comment by pskrbasu** [comment]
Resolved
